name: Deploy to vercel on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dkershner6/vercel-set-env-action@v3
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          teamId: ${{ secrets.ORG_ID }}
          projectName: jumpseat
          envVariableKeys: DATABASE_URL,AUTH_SECRET,SERP_KEY,NEXT_PUBLIC_POSTHOG_KEY,NEXT_PUBLIC_POSTHOG_HOST
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TARGET_DATABASE_URL: preview,development,production
          TYPE_DATABASE_URL: encrypted

          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          TARGET_AUTH_SECRET: preview,development,production
          TYPE_AUTH_SECRET: encrypted

          SERP_KEY: ${{ secrets.SERP_KEY }}
          TARGET_SERP_KEY: preview,development,production
          TYPE_SERP_KEY: encrypted

          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
          TARGET_NEXT_PUBLIC_POSTHOG_KEY: preview,development,production
          TYPE_NEXT_PUBLIC_POSTHOG_KEY: encrypted

          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}
          TARGET_NEXT_PUBLIC_POSTHOG_HOST: preview,development,production
          TYPE_NEXT_PUBLIC_POSTHOG_HOST: encrypted

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          scope: ${{ secrets.ORG_ID }}
          github-comment: false
